### ISSUE TITLE
Is it working?

### ISSUE THREAD

**Issue by pando85** [RyanNoelk/OpenEats#110]
I cannot get the front linked with the API :(

Running with `env_prod.list` configurated and  `docker-compose -f docker-prod.yml up -d`
```
api_1    | Session data corrupted
api_1    | Session data corrupted
api_1    | Session data corrupted
api_1    | Session data corrupted

nginx_1  | 172.21.0.1 - - [04/Feb/2017:08:28:52 +0000] "GET /bundle.js HTTP/1.1" 304 0 "http://127.0.0.1/" "Mozilla/5.0 (X11; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0" "-"
nginx_1  | 172.21.0.1 - - [04/Feb/2017:08:28:52 +0000] "GET /images/favicon.ico HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0" "-"
nginx_1  | 172.21.0.1 - - [04/Feb/2017:08:28:56 +0000] "GET /images/favicon.ico HTTP/1.1" 304 
```

What is this mean in `services/default.conf`?
```
#TODO: This file has the ports hard coded

upstream api {
  ip_hash;
  server api:API_PORT;
}

upstream node {
  ip_hash;
  server node:NODE_PORT;
}

```

**Comment by RyanNoelk** [comment]
Hey there!

So to answer your first question, yes it works. I have a similar instance running on my server. To answer your second questions about the ports in the nginx conf: I'm still playing around with easier and better ways to deploy the code into a production env. That is a hack that I'm using to link the docker containers ports with nginx.

So a few trouble shooting tips I can give:

Because of the above, if you are using a different set of ports than the ones in the env_stg.list (your env_prod.list file), be sure to change them in the docker-compose file as well.

Make sure your API is setup. In the readme I have a few commands that you need to run in order for gunicon (the API) to boot-up properly. 
`docker-compose -f docker-prod.yml  run --rm api bash`
```bash
./manage.py migrate
./manage.py collectstatic
./manage.py createsuperuser
./manage.py loaddata course_data.json
./manage.py loaddata cuisine_data.json
```

If you are having problems with the node packages you can also run:
- `docker-compose -f docker-prod.yml  run --rm api node`
- `npm install`

If you have done all that, you might wanna try just restarting all the containers. On first time boot things can get a bit weird and giving them a restart after the API and DB have been initialized fixes some of the issues.

If you have done all this and are getting issues, make sure that the API is accepting requests. You can log back into the API container and run a few cURL commands and see if the API is giving you anything back. Be use to use whatever port you have in the env file to run the below commands with as well:
curl http://localhost:8000/api/v1/recipe_groups/course/ should return:
```{"count":4,"next":null,"previous":null,"results":[{"id":3,"title":"Appetizer","author":1},{"id":1,"title":"Breakfast","author":1},{"id":4,"title":"Dessert","author":1},{"id":2,"title":"Entry","author":1}]}```


This project is still very early and very active with development. But the core features should totally work.

**Comment by pando85** [comment]
My API is working.
But my front is not well connected with my backend. I will investigate it.

Pdt: I saw the hack to replace the variables in nginx image.

**Comment by pando85** [comment]
I only can login in API, but I can't get nothing in front server.

**Comment by pando85** [comment]
Ok, I get it working, the problem was in `env_prod.list`

All URLs needs the same domain name:

```
# Database config
MYSQL_DATABASE=openeats
MYSQL_ROOT_PASSWORD=root

# Django config
API_URL=localhost:8000
DJANGO_SECRET_KEY=sdfsadfas32e98zsdvhhsnz6udvbksjdhfi4galshjfg
DJANGO_TIME_ZONE=Europe/Madrid
DJANGO_SETTINGS_MODULE=base.settings
DJANGO_DEBUG=True

# Node config
NODE_ENV=dev
NODE_URL=localhost:8080
NODE_PORT=8080
NODE_API_URL=http://localhost:8080
NODE_LOCALE=es
```

https://stackoverflow.com/questions/21783079/ajax-in-chrome-sending-options-instead-of-get-post-put-delete
