### ISSUE TITLE
Feature Roadmap

### ISSUE THREAD

**Issue by sixers** [RyanNoelk/OpenEats#117]
Hey,

Do you have a feature roadmap? I'd like to contribute to your project, but don't know what are the features you're working on or have planned. It would be good to add all of them as issues here, discuss, prioritize and maybe share development :)

A few ideas:

- Scraping recipes from popular sites. There are few projects we could reuse, e.g. https://github.com/hhursev/recipe-scraper
- Shared representation & automatic regognition of integredients
- Recipes full text search
- Nutrition info: micro and macroelements
- Menu composer -> Create a daily / weekly menu from recipes. It can work in several different ways: based on cuisine, based on products you have, etc.
- Shopping list
- Integration with shopping

**Comment by RyanNoelk** [comment]
Hey there,

So that is next on my list. I'm been trying to get the code to parity with a lot of the features in the original open eats while also redesigning/optimizing the core of the code. Once I get the shopping list ( #49 ) working, I want to focus on getting a wiki setup and creating a ton of docs/tests. 

So the usage for the app is intended for a single user or a small group. For my personal use, I would be an admin user and a few (about 5-6) friends and family would be normal users. Admin users can add other users to the project (no open sign-ups), make changes to the available Cuisines and Courses, and add to the homepage banner. Normal users just have the ability to add recipes and at some point maybe even rate recipes. The sign-ups would be handled my the admin user; either though the admin-panel, manually, or though so form we create in react.

As far as features go, if you have one that you really want to add go ahead and create an issue for it. We can talk about it and work on how to integrate it with whats currently there. If its something that is going to require new UI elements we can share mocks. I had a branch for the recipe scraping that is super old (and should be dropped at this point). So if your looking for something to do that would be awesome! 

Cheers!
-Ryan

**Comment by hermzz** [comment]
@sixers, in light of #118 a menu composer seems to be another interesting bit of functionality to add. Once the @RyanNoelk finishes the shopping list it'll probably become the next important element to add. 

I agree with what @RyanNoelk says in terms of creating issues to discuss their validity and potential implementation.

**Comment by hermzz** [comment]
@sixers, in light of #118 a menu composer seems to be another interesting bit of functionality to add. Once the @RyanNoelk finishes the shopping list it'll probably become the next important element to add. 

I agree with what @RyanNoelk says in terms of creating issues to discuss their validity and potential implementation.

**Comment by RyanNoelk** [comment]
I'm assigning this to myself. I'm going to use this to help be create a contributing file. See https://github.com/RyanNoelk/OpenEats/issues/123

**Comment by sadmansk** [comment]
+1 for Macro nutritions!

**Comment by RyanNoelk** [comment]
Going to close this as the app supports most the features listed here or has other tickets that address them. I'll create a issue for Nutrition info that has more info as far as implementation goes.
