### ISSUE TITLE
Create and use placeholder image for recipes without a photo.

### ISSUE THREAD

**Issue by hermzz** [RyanNoelk/OpenEats#82]
Possibly based of the image used in the `favicon`. @RyanNoelk is there an original somewhere?

**Comment by RyanNoelk** [comment]
There is a default image in the `api/base` here: https://github.com/RyanNoelk/OpenEats/blob/master/api/base/default.png

Running the management command `./manage imgur` will create the default images: https://github.com/RyanNoelk/OpenEats/blob/master/api/base/management/commands/imgur.py

the recipe serializer will return that image if it can't fine one: https://github.com/RyanNoelk/OpenEats/blob/master/api/v1/recipe/serializers.py#L15


This works fine, but thinking back on this, it doesn't make much since that its still in the api. The only reason its there is to allow users to use any image they want for the default. 

We should move the default image to the frontend and have the api return null for the image if it doesn't have one. Then let the frontend serve the image. Thoughts?

**Comment by hermzz** [comment]
`imgur` is a weird name for that command given what it does.

Yeah, that makes sense. We could at some point make the default image an option in the frontend configs.

**Comment by RyanNoelk** [comment]
`imgur` was a bad inside joke :). We should 100% rename it or remove it if we more the default image to the frontend.

**Comment by hermzz** [comment]
I was thinking of making something like this as the placeholder

<img width="150" alt="default" src="https://cloud.githubusercontent.com/assets/129883/22349093/19c862fc-e406-11e6-9f56-8cbc7a5bbb11.png">

But I think the current favicon is a way better representation _and_ looks better too. Hence my asking if there's a larger original somewhere. I can always generate it from the outlines if not.

**Comment by RyanNoelk** [comment]
I do like the favicon but I don't have a big image of it anywhere. Feel free to generate it if you like :)

**Comment by hermzz** [comment]
Hmmm. not sure we should be using an image from [another product](https://www.getmecooking.com/promote). That disclaimer is very vague. I'll see if I can find something creative commons we can just credit properly somewhere.

**Comment by hermzz** [comment]
As mentioned in the PR, I realised trying to find a more appropriate image was outside the scope of this task. I created a crappy placeholder for the time being.

**Comment by RyanNoelk** [comment]
Sounds fair. TBH I forgot where I got that favicon from. I'll start shopping around as well to see if I can find something. Let me know if you find a few you like.
